 # This is a basic workflow to help you get started with Actions

name: Publish package to Github

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Display new tag version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo New release: ${{ steps.semantic.outputs.new_release_version }}
       
     
